wip: draft docker image manager
molgenis/molgenis-service-armadillo pull request #174
Opened 2022-07-19 12:14 UTC by mswertz

2022-07-25 10:42 UTC, mswertz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement API to manage profiles](https://trello.com/c/hjiXHQcg/918-implement-api-to-manage-profiles)

2022-07-25 10:42 UTC, mswertz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement API to manage profiles](https://trello.com/c/hjiXHQcg/918-implement-api-to-manage-profiles)

2022-07-26 08:30 UTC, mswertz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pilot: Trying to use java api to start/stop profiles in Armadillo](https://trello.com/c/AxgiNAgo/917-pilot-trying-to-use-java-api-to-start-stop-profiles-in-armadillo)

2022-08-18 12:01 UTC, tommydeboer requested changes
As we discussed on slack, here are some other points:

- Use system persistence instead of docker labels
- Use `application.yml` to configure initial containers:
  - Don't use docker-compose because then we need labels
  - Ops can specify default setup if they like
  - Persistence is populated with initial values
  - Devs don't need to do anything extra

2022-08-18 12:07 UTC, tommydeboer commented
**Issue:**
1. Create a `test` profile (following the test script)
2. `GET /profiles` gives:
```json
{
  "current": "default",
  "available": [
    "default",
    "test"
  ]
}
```
3. `POST /select-profile` with "test" gives:
```json
{
  "timestamp": "2022-08-18T12:06:20.508+00:00",
  "status": 404,
  "error": "Not Found",
  "message": "Profile: \"test\" not found",
  "path": "/select-profile"
}
```

2022-08-18 13:18 UTC, mswertz commented on armadillo/src/main/java/org/molgenis/armadillo/controller/DatashieldProfileController.java
> +    this.auditEventPublisher.audit(principal, "List armadillo profiles", Map.of());
ah, now I understand the weird pattern of audit(function). Thanks makes sense that you can then also audit exceptions. I thought these would be captured centrally but then you don't know what the context was of the exception. Nice.

2022-08-18 13:19 UTC, mswertz commented on armadillo/src/main/java/org/molgenis/armadillo/controller/DatashieldProfileController.java
> +  public void addProfile(Principal principal, @RequestBody ProfileConfigProps profileConfigProps)
I believe these options are also necessary? They were used for the 'seed' value. So I conclude we hardcode this seed value then in new value object so we can simplify this payload, agreed?

2022-10-19 10:43 UTC, mswertz reviewed
I am happy for this code to be merged.

What remaining points do you want to change @tommydeboer ?

(I can't approve because I created the PR)

2022-11-02 07:23 UTC, tommydeboer approved these changes

2022-11-03 13:53 UTC, merged