Add non interactive support.
molgenis/molgenis-service-armadillo pull request #527
Opened 2023-10-30 07:30 UTC by clemens-tolboom

2023-11-03 14:12 UTC, marikaris requested changes
I think in non-interactive mode, want to automatically remove admin permissions from the oidc user (and turn them back on again later). Or is there a reason you didn't choose to do that?

2023-11-03 14:14 UTC, marikaris commented
![](https://github.trello.services/images/mini-trello-icon.png) [non-interactive support for release test script](https://trello.com/c/PtqySfv1/1109-non-interactive-support-for-release-test-script)

2023-11-09 09:11 UTC, clemens-tolboom commented
I added timing the file upload (#526 to blame)

2023-11-10 14:16 UTC, marikaris approved these changes

2023-11-14 08:42 UTC, merged