test: xenon-omics
molgenis/molgenis-service-armadillo pull request #716
Opened 2024-03-21 16:01 UTC by timcadman

2024-03-25 11:32 UTC, clemens-tolboom commented
### Cannot complete script

This happend twice

```
ℹ Checking if rda dir exists
✔ prepare-resources passed!
ℹ Uploading resource file to http://localhost:8080/ into project [avindaw3w7]
⠏✔ upload-resource passed!
ℹ Uploading resource file to http://localhost:8080/ into project [avindaw3w7]
⠏✔ upload-resource passed!
ℹ Uploading resource file to http://localhost:8080/ into project [avindaw3w7]
⠏✔ upload-resource passed!
ℹ Uploading resource file to http://localhost:8080/ into project [avindaw3w7]
⠏✔ upload-resource passed!
✔ create_resource passed!
✔ create_resource passed!
✔ create_resource passed!
✔ create_resource passed!
Compressing...
Uploaded exposome/exposures
Compressing...
Uploaded exposome/description
Compressing...
Uploaded exposome/phenotypes
Compressing...
Uploaded exposome/exposomeSet
  Assigned all resource (exposures <- ...) [=============================================] 100% / 0s
  Assigned all resource (description <- ...) [===========================================] 100% / 0s
  Assigned all resource (phenotypes <- ...) [============================================] 100% / 0s
  Assigned all resource (exposomeSet <- ...) [===========================================] 100% / 0s
  Assigned expr. (description <- as.resource.data.frame(description)) [==================] 100% / 2s
  Assigned expr. (exposures <- as.resource.data.frame(exposures)) [======================] 100% / 1s
  Assigned expr. (phenotypes <- as.resource.data.frame(phenotypes)) [====================] 100% / 0s
ℹ Checking ds.loadExposome
  Assigned expr. (exposome_object <- loadExposomeDS(exposures, description, phenotypes, 'idnum', ...Error: There are some DataSHIELD errors, list them with datashield.errors()
Execution halted
```

2024-04-08 14:11 UTC, marikaris requested changes

2024-04-08 14:11 UTC, marikaris commented on scripts/release/test-cases/xenon-omics.R
> +    gwas_results <- ds.metaGWAS(
This line fails for me: 
```
$armadillo
[1] "Execution failed: 400 Bad Request: \"{\"status\":\"400\",\"key\":\"REvaluationRuntimeException\",\"args\":[],\"message\":\"Error in if (idx <= length(redo.index)) idx <- redo.index[idx] else idx <- idx -  : \\n  argument is of length zero\\n\"}\""
```

2024-04-08 14:11 UTC, marikaris commented on scripts/release/test-cases/xenon-omics.R
> +      conns = conns, symbol = .x, expr = as.symbol(paste0("as.resource.object(", .x, ")"))
Can't you parameterise `resolve_many_resources` in `comming-functions.R` to reuse here?

2024-04-25 08:47 UTC, marikaris approved these changes

2024-04-25 10:46 UTC, merged