Create minor-release-update.md
molgenis/molgenis-service-armadillo pull request #771
Opened 2024-07-15 13:43 UTC by RubenOPS

Creating a minor release update manual.

2024-07-16 10:55 UTC, timcadman requested changes

2024-07-16 10:55 UTC, timcadman commented on docs/minor-release-update.md
> +First, stop all profiles using the Armadillo UI.
Could you add a little more detail where/how?

2024-07-16 10:55 UTC, timcadman commented on docs/minor-release-update.md
> +Make a note of the version number ie. `v4.1.3` as you need to download some files from the terminal using the updatescript.
Current version number?

2024-07-16 10:55 UTC, timcadman commented on docs/minor-release-update.md
> +Make a note of the version number ie. `v4.1.3` as you need to download some files from the terminal using the updatescript.
Should updatescript be update script?

2024-07-16 10:55 UTC, timcadman commented on docs/minor-release-update.md
> +## 6. start profiles
'Start profiles'

2024-07-16 12:48 UTC, timcadman approved these changes

2024-07-17 11:22 UTC, erikzwart approved these changes
Functional test of local Armadillo update from 4.7.1 to 4.8.1, update was successful.
![image](https://github.com/user-attachments/assets/373d3851-8924-429b-9f52-fd87a28cae5c)

2024-09-17 14:11 UTC, marikaris commented
Can we merge this? @RubenOPS

2024-09-18 06:43 UTC, RubenOPS commented
Yes i think we can @marikaris

2024-09-19 06:58 UTC, merged