feat: kill r processes
molgenis/molgenis-service-armadillo pull request #98
Opened 2020-08-18 10:50 UTC by fdlk

2020-08-18 21:32 UTC, fdlk commented on armadillo/src/main/java/org/molgenis/armadillo/ArmadilloSession.java
> -  public synchronized void sessionCleanup() {
No longer needs to wait for evaluation to be finished, it kills the process instead!

2020-08-19 11:01 UTC, sidohaakma commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cleanup stale sessions on the Rserve environment](https://trello.com/c/Y3NuiRsk/214-cleanup-stale-sessions-on-the-rserve-environment)

2020-08-19 11:40 UTC, sidohaakma requested changes

2020-08-19 11:40 UTC, sidohaakma commented on r/src/main/java/org/molgenis/r/service/ProcessServiceImpl.java
> +              rExecutorService.execute(COUNT_RSERVE_PROCESSES_COMMAND, connection).asList().get(0))
Nice to use the RExecutorService here!

2020-08-19 11:40 UTC, sidohaakma commented on armadillo/src/main/java/org/molgenis/armadillo/ArmadilloSession.java
> +        return connection;
Maybe log the pid as well? We ports, but pid's would be useful as well concerning you can execute a api call to kill it?
Or do we use the connection to determine the pid using the actuator endpoints?

2020-08-20 11:20 UTC, fdlk commented on r/src/main/java/org/molgenis/r/service/ProcessServiceImpl.java
> +              rExecutorService.execute(COUNT_RSERVE_PROCESSES_COMMAND, connection).asList().get(0))
Yes, I'd forgotten all about it :D

2020-08-20 12:02 UTC, sidohaakma approved these changes

2020-08-20 12:02 UTC, merged